### ISSUE TITLE
UL inside OL has numerals.

### ISSUE THREAD

**Issue by joh-lin** [joh-lin/marp-themes#3]

**Comment by joh-lin** [comment]
And other way around.

**Comment by Fiores7** [comment]
It seems you are working on a nested list. 
If you wish to not have numerals in a < ol > list, specify the type attribute of the < ol > list.

You can have an ol listed with an uppercase letter:
 < ol type="A" >

Or with lowercase letters:
< ol type="a" >
  
< ol type="I" >The list items will be numbered with uppercase roman numbers
< ol type="i" >The list items will be numbered with lowercase roman numbers

Please take a look at the attached code.
[nested list HTML.txt](https://github.com/user-attachments/files/16582253/nested.list.HTML.txt)
